title: My first site with jekyll
author: GitHub User
email: elias84631@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Hello, my name is Elias and i study programming

# social links
twitter_username: your-twitter-handle # DO NOT include the @ character, or else the build will fail!
github_username:  elia84631 # DO NOT include the @ character, or else the build will fail!

show_excerpts: true # set to false to remove excerpts on the homepage
theme: minima
